package com.grand.enoteboot.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table enote_article
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ArticleVO{
    /** ID*/
    private Long id;

    /** 文章标题*/
    private String title;

    /** 位置（0：首页:1：海外扩展:2：国际对接）*/
    private Integer location;

    /** 标签:（0：公告，1：活动，2：专题）*/
    private String tags;

    /** 所属区域*/
    private Long areaId;

    /** 封面图*/
    private String coverImgPath;

    /** 文章概要*/
    private String summary;

    /** 排序号*/
    private Integer sortNo;

    /** 服务状态(0=上架，1=已下架)*/
    private Integer status;

    private String statusStr;

    /** 是否推荐 (0=已推荐，1=未推荐)*/
    private Integer recommendFlag;

    private String recommendStr;

    /** 删除标记（0=未删除，1=已删除）*/
    private Integer deleteFlag;

    /** 创建时间*/
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createTime;

    /** 创建人*/
    private Long createId;

    /** 最后修改时间*/
    private Date updateTime;

    /** 最后修改人*/
    private Long updateId;

    /** 文章内容*/
    private String content;
}