package com.grand.enoteboot.entity;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table enote_permission
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Permission {
    /** 自增id*/
    private Long id;

    /** 类型（1=前台、中台；2=后台）*/
    private Integer permType;

    /** 资源名称*/
    private String name;

    /** 资源地址*/
    private String url;

    /** 父资源*/
    private Long parentId;

    /** 排序*/
    private Integer sortNo;

    /** 是否叶子节点*/
    private Integer isLeaf;

    /** 状态*/
    private Integer status;

    /** 资源描述*/
    private String description;

    /** 创建人*/
    private Long createId;

    /** 创建时间*/
    private Date createTime;

    /** 更新人*/
    private Long updateId;

    /** 更新时间*/
    private Date updateTime;

    /** 删除标识(0:未删除；1:已删除)*/
    private Integer isDelete;
}