package com.grand.enoteboot.entity;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table enote_user_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class UserRole {
    /** 自增id*/
    private Long id;

    /** 用户id*/
    private Long userId;

    /** 角色id*/
    private Long roleId;

    /** 类型（1=前台、中台；2=后台）*/
    private Short permType;
}