package com.grand.enoteboot.dao;

import com.grand.enoteboot.entity.Article;

import java.util.List;

public interface ArticleDao {

    /**
     * @return
     */
    List<Article> findAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Article record);

    List<Article> findAllDesc();

    Article findById(Long id);

    Integer delete(Long id);
}