package com.grand.enoteboot.dao;

import com.grand.enoteboot.entity.Permission;

import java.util.List;

public interface PermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Permission record);

    List<Permission> findAll();
}