package com.grand.enoteboot.dao;

import com.grand.enoteboot.entity.UserRole;

import java.util.List;

public interface UserRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enote_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRole record);

    List<UserRole> selectByUserId(Long userId);
}